import pandas as pd
df=pd.read_csv(r"pandas\calout.csv")
print(df)
print(df.head(5))
print(df.tail(3))
print(df.info())
print(df.describe())
print("Columns:", df.columns)
print(df["number"])
print(df[["number","square","cube","factorial"]])
print(df.loc[:,["number","square"]])
print(df.iloc[:,0:5])
print(df[df["number"]>8])
print(df[df["cube"]==512])
print(df.sort_values(("number")))
print(df.sort_values("factorial",ascending=False))